//local host
###
GET http://localhost:8080/diet

###
GET http://localhost:8080/goal

###
POST http://localhost:8080/goal HTTP/1.1
Content-Type: application/json

{
    "health":{
        "description": "This is my health description",
        "weight": "100",
        "calories": "2000",
        "heartrate": "85"
    },
    "physical": {
            "description": "This is my physical description",
            "liftName": "Curl",
            "weightTime": "10"
        }
}

###
GET http://localhost:8080/diet

###
POST http://localhost:8080/diet HTTP/1.1
Content-Type: application/json

{
   "diet":{
        "description": "Loose 10 lb's in 5 weeks",
        "dietName": "Loose 10 diet",
        "calories": "1800",
        "protein": "200",
        "carbs": "900",
        "sugar": "0",
        "weight": "175"
   }
        
}
